### ISSUE TITLE
GoTube: streamingData is missing from this video

### ISSUE THREAD

**Issue by raresraf** [Marethyu12/gotube#18]
Hi there,

What is the possible cause of the following error?

```
$ ./gotube https://www.youtube.com/watch?v=nVjsGKrE6E8
GoTube: streamingData is missing from this video 'nVjsGKrE6E8'
```

However, the example provided in README worked :)
```
$ ./gotube https://www.youtube.com/watch?v=2fsMUqYix0c
<nil>
$ #Downloaded successfully
```

**Comment by Marethyu12** [comment]
@raresraf  Thanks for opening this issue. It is caused by this block of code:
```
if videoData["streamingData"] == nil {
	return fileName, downloadURL, fmt.Errorf("GoTube: streamingData is missing from this video '%v'", id)
}
```

It seems the video you are trying to download does not have streaming data which is necessary for a successful download. Unfortunately, GoTube at this moment only works for certain videos not the video you linked. Possibly, I will make it work for all kinds of videos. In the meantime, try other downloaders like youtube-dl.

**Comment by raresraf** [comment]
Thanks for the reply.
Have a nice day!
